### ISSUE TITLE
Confirm default commission rates for broker

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#102]
Current rates:
Broker: 50
Agent: 12.5
Client: 3

**Comment by hutch77** [comment]
@patricksheedy  talked through with Jim, we will set the defaults to:

Broker: 50
Agent: 0
Client: 0

We will let the Broker manage their commission rates because they will vary wildly and it would be hard to determine a standard default for all of them.
