### ISSUE TITLE
Card Details - Search and View

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#110]
Wire up card details view to display data associated with the card.

define and implement search parameters to bring up a card in a search

**Comment by patricksheedy** [comment]
Additional details needed for the view:
There is a table on the screen called "Hotel & Condo Benefits Detail View". Does this table also need to include Shopping and Dining?

The summary for the table has "Hotel Savings". What about Condo (and shopping/dining)?

**Comment by patricksheedy** [comment]
Placeholder procs for this page are: GetCardDetails, GetCardUsage

**Comment by patricksheedy** [comment]
Need these fields added to GetCardDetails:
ActivatedBy
Commission Paid
Commission Owed

**Comment by patricksheedy** [comment]
GetCardUsage - We need codes that generate results for testing. I see codes that have activities but the proc doesn't return any data for them.

**Comment by patricksheedy** [comment]
This is implemented.
