### ISSUE TITLE
ReportProductionDetails is returning duplicate rows

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#113]
Duplicate rows are being returned. Maybe add "distinct" to the query?

Sample:
EXECUTE @RC = [dbo].[ReportProductionDetails] 
   '1/1/2015' -- @BookingStartDate
  ,'1/1/2025' -- @BookingEndDate
  ,'1/1/2015' -- @CheckOutStartDate
  ,'1/1/2025' -- @CheckOutEndDate
  ,0 --@StartRowIndex
  ,10000  -- @NumberOfRows
  ,'DEFAULT' -- @SortColumn
  ,'ASC' -- @SortDirection
  ,4 -- @BrokerId
  ,null -- @AgentId
  ,null -- @ClientId
  ,'' -- @Search
  ,null -- @TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
