### ISSUE TITLE
ReportProductionDetails: Needs to be updated to support Agents

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#116]

**Comment by hutch77** [comment]
I'm not sure what this issue is, but sounds like something that needs to be done for the Prod Reports for Agents that we will be doing in v1.1

**Comment by patricksheedy** [comment]
I'm not sure if this is needed anymore. I don't see a way to query for agents in the UI.

**Comment by patricksheedy** [comment]
Closing - doesn't seem to be useful. If there is a problem with the reports then create a new issue with more detail.
