### ISSUE TITLE
ReportProductionByBroker returns 1 row when there should be 0 rows

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#118]
Example query:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionBybroker] 
   45
  ,'1/1/2010' -- @BookingStartDate
  ,'1/1/2020' -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,0 -- @StartRowIndex
  ,30000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
