### ISSUE TITLE
ReportProductionByBroker: PaidDate is not available

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#119]
Sample Query: 
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionBybroker] 
   4
  ,'1/1/2010' -- @BookingStartDate
  ,'1/1/2020' -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,0 -- @StartRowIndex
  ,30000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
@patricksheedy Ok I added @PaidDate after @CheckOutDate.  Right now there are no paid dates in the system so it will return nothing.  So if you pass null then it still returns data like below

DECLARE @totalcount int
EXECUTE [dbo].[ReportProductionBybroker]
4
,'1/1/2010' -- @bookingstartdate
,'1/1/2020' -- @bookingenddate
,'1/1/2010' -- @checkindate
,'1/1/2020' -- @checkoutdate
, NULL -- @PaidDate
,0 -- @startrowindex
,30000 -- @numberofrows
,@totalcount OUTPUT
GO
