### ISSUE TITLE
ReportProductionByClient returns 1 row when there should be 0 rows

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#120]
Example:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionByClient] 
   8 -- @ClientId
  ,null -- @BrokerId
  ,null -- @PaymentStatus
  ,'1/1/2010' -- @BookingStartDate
  ,'1/1/2020' -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,0 -- @StartRowIndex
  ,1000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
