### ISSUE TITLE
ReportProductionClient should return client's company name

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#121]
Sample Query:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionByClient] 
   5 -- @ClientId
  ,null -- @BrokerId
  ,null -- @PaymentStatus
  ,'1/1/2010' -- @BookingStartDate
  ,'1/1/2020' -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,0 -- @StartRowIndex
  ,1000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Done
