### ISSUE TITLE
Index needed on Bookings.RSIId

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#122]
The reporting procs are doing a Clustered Index Scan on the Bookings table that is taking up 94% of the time. An index should be added to speed this up. 

Repro:
Turn on "Include Actual Execution Plan".
Run this query:
DECLARE @totalcount int
EXECUTE [dbo].[ReportProductionDetails]
'1/1/2015' -- @bookingstartdate
,'1/1/2025' -- @bookingenddate
,'1/1/2015' -- @checkoutstartdate
,'1/1/2025' -- @checkoutenddate
,0 -- @startrowindex
,30000 -- @numberofrows
,'DEFAULT' -- @sortcolumn
,'ASC' -- @sortdirection
,null -- @brokerid
,null -- @agentid
,5 -- @clientid 
,'' -- @search
,@totalcount OUTPUT
GO

**Comment by DennisRSI** [comment]
Done
