### ISSUE TITLE
CommissionReport: Database procedures needed

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#124]
When logged in as Admin user can query by: Broker and Source
[Mockup](http://arcadiaresorts.com/RSI/dashboard/admin-report-comm-broker2.html)

When logged in as Broker user can query by: Client
I believe this would then group by campaign. I don't think there is a mockup that shows this.

Both queries should accept a payment status field (see Admin mockup).

**Comment by DennisRSI** [comment]
Done
ReportCommissionBySource
ReportCommissionByBroker
