### ISSUE TITLE
Assigning agent to client deletes some information

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#125]
When creating a client, filled out all necessary information including "contact name" and "office phone". After creation, I assigned an Agent to the client and it over-wrote the contact name (blank now) and the office phone (blank now).

Additionally, the Client Management screen does not display the Agent that I assigned to that client.

![missing info](https://user-images.githubusercontent.com/16338069/42046432-7d8f6eac-7ac3-11e8-8339-0677249e9a7e.png)

![wiped-out-info](https://user-images.githubusercontent.com/16338069/42046450-8c777de2-7ac3-11e8-80b0-678e02f70069.png)

**Comment by patricksheedy** [comment]
Fixed in the QA database.
