### ISSUE TITLE
Card Dist by Broker table (Admin): Not updating new broker info

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#128]
Created a Broker (Chris Hutchison) and the table updates with the new broker name, but I created 1 card with 150 activations and the table does not reflect this. CTL-F5 does not refresh the table to show it either.

![missing data](https://user-images.githubusercontent.com/16338069/42047248-6623c0d6-7ac5-11e8-903d-2e7a794b63a5.png)

**Comment by patricksheedy** [comment]
Repro:
EXECUTE @RC = [dbo].[DashboardDistributionAdmin] 
   1
GO

There is a BrokerId column in the UnusedCodes table that is set to an incorrect value. The proc is querying for this.

Problematic line is:
`			SELECT SUM(C.NumberOfUses)
			FROM UnusedCodes U  INNER JOIN 
			Campaigns C ON U.CampaignId = C.CampaignId
			WHERE U.BrokerId = b.BrokerId AND U.CodeType = 'Virtual'`

Should the last line start with `WHERE C.BrokerId'` instead? Need to confirm with @DennisRSI

**Comment by patricksheedy** [comment]
I created a campaign and the row in the UnusedCodes table was written with a BrokerId of 4. I debugged the code and it looks like when the web site calls GenerateCodes it passes in the correct BrokerId.
