### ISSUE TITLE
Admin view - Broker Table commission rates

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#129]
Dennis has updated the table to reflect a 50% commission rate for all brokers but the table only shows a few that have a commission rate that's not 0. Good news is the broker I manually created (Chris Hutchison) is showing the commission rate I set correctly.

![commission-rates](https://user-images.githubusercontent.com/16338069/42047831-0db2ef10-7ac7-11e8-83b9-c74e7872bd33.png)

**Comment by patricksheedy** [comment]
The web app is correct. These commissions are 0 in the database.

**Comment by patricksheedy** [comment]
Fixed in QA database.
