### ISSUE TITLE
ReportProductionDetails execution error

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#131]
Run:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionDetails] 
   '1/1/2015' -- @BookingStartDate
  ,'1/1/2025' -- @BookingEndDate
  ,'1/1/2015' -- @CheckOutStartDate
  ,'1/1/2025' -- @CheckOutEndDate
  ,0 -- @StartRowIndex
  ,30000 -- @NumberOfRows
  ,'DEFAULT' -- @SortColumn
  ,'ASC' -- @SortDirection
  ,4 -- @BrokerId
  ,null -- @AgentId
  ,null -- @ClientId
  ,'' -- @Search
  ,@TotalCount OUTPUT
GO

Error:
Msg 207, Level 16, State 1, Procedure ReportProductionDetails, Line 42 [Batch Start Line 5]
Invalid column name 'ClubCommissionDue'.
Msg 207, Level 16, State 1, Procedure ReportProductionDetails, Line 42 [Batch Start Line 5]
Invalid column name 'ClubCommissionDue'.

**Comment by DennisRSI** [comment]
Fixed
