### ISSUE TITLE
Available Activations showing incorrectly in table (broker/admin)

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#134]
Created new broker (Testington McBugfinder) > client > campaign and assigned 1 card with 150 activations. The tables show 1 card and 1 activation:

This is a continuation of #128 

Broker view:
![avail-activations](https://user-images.githubusercontent.com/16338069/42113026-82a73158-7baf-11e8-8ca0-88cb813a9f59.png)

Admin view:
![avail-activations-admin](https://user-images.githubusercontent.com/16338069/42113033-874f033e-7baf-11e8-8818-e9c58b6299da.png)

**Comment by DennisRSI** [comment]
Fixed
