### ISSUE TITLE
ReportCommissionByBroker doesn't work on production database

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#135]
Query is below. When run on the dev database it returns rows. When run on the prod database it returns nothing. 

DECLARE @TotalCount int
EXECUTE  [dbo].[ReportCommissionByBroker] 
   4
  ,null -- @BookingStartDate
  ,null -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,null -- @PaidDate
  ,0 -- @StartRowIndex
  ,1000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
