### ISSUE TITLE
DashboardDistributionAdmin procedure doesn't work on production

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#136]
The procedure doesn't work in the production database, but does work in the dev database.

Repro:
USE [RSICodeGenerators]
GO

EXECUTE [dbo].[DashboardDistributionAdmin] 
   0
GO

Error:
Msg 512, Level 16, State 1, Procedure DashboardDistributionAdmin, Line 19 [Batch Start Line 2]
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
The statement has been terminated.

**Comment by DennisRSI** [comment]
Fixed
