### ISSUE TITLE
ReportCommissionBySource doesn't use Check-in or Check-out dates

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#140]

**Comment by DennisRSI** [comment]
It Seems to be working for me.  See test below.

USE [RSICodeGenerators]
GO

DECLARE	@return_value int,
		@TotalCount int

EXEC	@return_value = [dbo].[ReportCommissionBySource]
		@Source = NULL,
		@BrokerId = NULL,
		@BookingStartDate = NULL,
		@BookingEndDate = NULL,
		@CheckInDate = '2018-06-01',
		@CheckOutDate = '2018-06-04',
		@PaidDate = NULL,
		@StartRowIndex = 0,
		@NumberOfRows = 100,
		@TotalCount = @TotalCount OUTPUT

SELECT	@TotalCount as N'@TotalCount'

**Comment by patricksheedy** [comment]
Proc needs to be updated in DEV.
