### ISSUE TITLE
ReportCommissionByBroker: Returns the same data for all BrokerId values

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#146]
The proc should return data only for the broker supplied in the BrokerId parameter. It is returning data for multiple brokers.

Example:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportCommissionByBroker] 
   4 -- @BrokerId
  ,'1/1/2010' -- @BookingStartDate
  ,'1/1/2020' -- @BookingEndDate
  ,'1/1/2010' -- @CheckInDate
  ,'1/1/2020' -- @CheckOutDate
  ,'All' -- @PaidStatus
  ,0 -- @StartRowIndex
  ,10000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
