### ISSUE TITLE
ReportProductionByClient returns data for all clients

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#149]
This proc should only return data for the specified ClientId.

Repro:
DECLARE @TotalCount int
EXECUTE  [dbo].[ReportProductionByClient] 
   1 -- @ClientId
  ,null -- @BrokerId
  ,null -- @BookingStartDate
  ,null -- @BookingEndDate
  ,null -- @CheckInDate
  ,null -- @CheckOutDate
  ,'All' -- @PaidStatus
  ,0 -- @StartRowIndex
  ,1000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
