### ISSUE TITLE
Production Report By Campaign: What does it look like?

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#151]
There isn't a mockup for running a Production Report By Campaign (and selecting all) when logged in a broker.

What should this report show?

**Comment by hutch77** [comment]
Production Report by Campaign would look similar to prod by source, just more granular and show the individual transactions of the campaign.

1. Each table is a campaign
2. Fields: Member Name, Internet Price, You Pay Price, Member Savings, Transaction Date
3. Tally the prices/savings at the bottom of the table like we do with the other reports
