### ISSUE TITLE
ReportProductionByClient should group by campaign

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#152]
Mockup:
http://arcadiaresorts.com/RSI/dashboard/admin-report-prod-client2.html

Repro:
DECLARE @TotalCount int
EXECUTE [dbo].[ReportProductionByClient] 
   3 -- @ClientId
  ,null -- @BrokerId
  ,null -- @BookingStartDate
  ,null -- @BookingEndDate
  ,null -- @CheckInDate
  ,null -- @CheckOutDate
  ,'all' -- @PaidStatus
  ,0 -- @StartRowIndex
  ,100000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
