### ISSUE TITLE
Need clarification for Broker's Commission Report by client

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#153]
Broker Mockup: http://arcadiaresorts.com/RSI/dashboard/reports-commission-clients2.html

This is different than the other Commission reports. Is this the way it is supposed to be?

For example, when the Admin runs the report they get this:
http://arcadiaresorts.com/RSI/dashboard/admin-report-comm-broker2.html

I would assume that the Broker should get a table for each client, the table would then be broken down by campaign. This is also how the Production Report By Client works for Admin.

**Comment by hutch77** [comment]
That works - how you described in the last paragraph.

So each table is a client of the broker that's logged in. The field "Client" becomes "Campaign" and lists the campaigns for the client in that table. The rest of the fields remain the same (# cards, Transactions, Internet Price, etc)

**Comment by patricksheedy** [comment]
This report will be implemented once #154 is fixed.
