### ISSUE TITLE
ReportCommissionByClient should group by campaign

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#154]
Repro:
DECLARE @TotalCount int
EXECUTE  [dbo].[ReportCommissionByClient] 
   null -- @BrokerId
  ,5 -- @ClientId
  ,null -- @BookingStartDate
  ,null -- @BookingEndDate
  ,'7/6/2017' -- @CheckInDate
  ,'7/6/2018' -- @CheckOutDate
  ,'All' -- @PaidStatus
  ,0 -- @StartRowIndex
  ,10000 -- @NumberOfRows
  ,@TotalCount OUTPUT
GO

**Comment by DennisRSI** [comment]
Fixed
