### ISSUE TITLE
GetCardDetails procedure needed

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#155]
I created a placeholder for GetCardDetails on Dev. This procedure needs to be filled in.

**Comment by DennisRSI** [comment]
Do we have a mockup of card details page so I can pull the correct info

**Comment by DennisRSI** [comment]
Done except for what is the activated By field suppose to show?

**Comment by patricksheedy** [comment]
This is completed.
