### ISSUE TITLE
Points Balance on Production Report is wrong

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#167]
Points balance doesn't appear to be calculating how much is left on a member's card (points balance). For instance, a member with a $200 card has used the card and the points balance shows $200 still remaining on the card.

Points balances are always extremes - either $0 left or the full amount of the original card.

![points-balance](https://user-images.githubusercontent.com/16338069/42772506-4a8cdf22-88f0-11e8-9d8d-3615c3510cb5.png)

**Comment by DennisRSI** [comment]
Waiting for Chris to look at the fix I put in QA.  If ok will deploy to console and this issue can be closed.
