### ISSUE TITLE
Is Commission Rate calculating correctly?

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#170]
Screenshot: Ron White is listed at 50% commission rate. When I pull a Commission report, I see that he is owed $20.24 on a total member savings of $20.37. I would expect his commission to be 50% of the $20.37.

![commission-wrong](https://user-images.githubusercontent.com/16338069/42783296-3104a9a6-8911-11e8-91d4-424f6d4a1d7f.png)

**Comment by patricksheedy** [comment]
The Commission Earned column is being calculated from a database column called PartnerShare. While the MemberSavings is being calculated from CustomerDiscount. I'm guessing that these are storing different values. I'm not sure what the purpose of each of these columns is and why the proc is using different values. @DennisRSI will have to answer that.

**Comment by DennisRSI** [comment]
Yes, customer discount (Points used) is taking the internet price - you pay price.  It has nothing to do with commission earned.  The example above the commissions are from three bookings 22.24 + 22.13 + 4.11 Commissions earned = 48.48 total commissions and 50 percent of that is the 24.24 showing.

**Comment by hutch77** [comment]
@DennisRSI So does that mean the Member Savings is off? It sounds like the member savings on those three transactions for that client were $48.48 rather than $20.37?
