### ISSUE TITLE
CREATE CAMPAIGN DOESN'T WORK

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#173]
Walked through creating a campaign with Walter. Filled all fields correctly but when we hit the "Create Campaign" button at the bottom, nothing happens. Campaign not created. This worked in QA, not working in production.

**Comment by patricksheedy** [comment]
GenerateCodes was missing the "select top 1 * from codes" at the bottom of the proc. The proc has been updated.
