### ISSUE TITLE
Report Discrepancy in Member Savings

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#175]
Multiple reports are showing different data on Member Savings:

If you pull:
Prod Report > By Client > Creative Charity Auctions, you get Member Savings of $20.37

If you pull:
Prod Report > By Client > All Clients and go to Creative Charity Auctions, you get Member Savings of $40.74

If you pull:
Commission Report > By Source > Ron White (broker of Creative Charity Auctions), you get Member Savings of $40.74

**Comment by patricksheedy** [comment]
This is probably a difference between ReportProductionDetails and ReportProductionByClient. At the moment I'm not sure what the difference is. @DennisRSI would probably know, but if not I can look more into it on Thursday.

**Comment by DennisRSI** [comment]
Fixed, the issue was multiple cards for activated for same users.  I made the changes to both QA and console.  I tested the reports and they are still working.
