### ISSUE TITLE
Sub-Agent System

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#183]
Brokers need to be able to add multiple levels of Agents under them. The first will be the "Primary Agent" and each level underneath the Primary will be labeled SubAgent1, SubAgent2, SubAgent3, etc.

Needs to be a maximum of 5 Agents deep:

1. Primary Agent
2. SubAgent 1
3. SubAgent 2
4. SubAgent 3
5. SubAgent 4

The Commission Structure of a Broker and his/her subagents is outlined on this Google Sheet: https://docs.google.com/spreadsheets/d/1APv-Sm8wd3dtSfLbM8kI2ax0EJEsLVTNydAxqF-ZSPc/edit?usp=sharing

**Comment by patricksheedy** [comment]
Additional clarification on commissions is needed. Can commissions be changed when the agent is created? Or does it somehow get determined automatically based on the parent agent/broker?

The Add Agent screen currently has a field for setting the commissions, how should that be handled based on the above clarification.

**Comment by hutch77** [comment]
Commission cannot be changed once created. If a change needs to be made post creation, it would have to be done manually like it is with brokers, agents and clients now

**Comment by patricksheedy** [comment]
From today's call:
On the commission report, for Admin user, show an additional column for agent name. If there are one or more agents for the client then multiple rows will be returned for each client. Each agent will have the commission amounts for that agent.

**Comment by patricksheedy** [comment]
Subagents are implemented. If there are issues found with the subagent system then new issues should be opened.
