### ISSUE TITLE
Production Reports for Clients/Agents

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#184]
Clients and Agents need to be able to access Production Reports for their campaigns.

Also possibly related: #116

**Comment by patricksheedy** [comment]
Activation Report: ReportActivations stored proc needs to be updated to support campaigns.

**Comment by patricksheedy** [comment]
Production Report for Client is loading data. Verified with asigeneral@example.com client account.

**Comment by patricksheedy** [comment]
Production Report for Agent is loading data. Verified with asiagent@example.com (created this agent and assigned to asigeneral@example.com client).
