### ISSUE TITLE
Brokers should be able to create Agent accounts

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#188]
Currently, brokers have to contact an admin (Walter) to create Agents for them. They should be able to create their own agents within the system as an admin does.

**Comment by patricksheedy** [comment]
What is the UI to implement this feature?

**Comment by hutch77** [comment]
The UI would be exactly the same as when an Admin creates an agent - they currently already have this capability. Is there a feature of this I'm not taking into account that needs new UI development?

**Comment by patricksheedy** [comment]
In looking through the site it seems that there is a way to do this. Logged in as a broker select the menu in the upper right. Then click the profile link. Agents can be added on this screen.
