### ISSUE TITLE
Agent Production Report: Remove "Commission Earned" Column in Tables

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#218]
Commission Earned column is pulling the Broker commission rate, should be the Agent's. Remove that column until the report proc can be updated for Agents. Make sure this doesn't affect the Broker Production report, so only remove it from the UI of the Agent login.

**Comment by hutch77** [comment]
Issues on the Agent Production Report:

1. Dropdown is showing duplicate of Crosfit Gym (I'll give you credentials so you can see this)
2. The tables are showing the duplicate of Crosfit Gym as well (see screenshot)
3. Broker Commission is showing in the Client Totals line item under the tables (see screenshot)
4. The Member Savings in the final Summary at the bottom is adding those two duplicate tables (screenshot)

![agent-report-errors](https://user-images.githubusercontent.com/16338069/53923540-4cabfa80-403e-11e9-8d3e-3e47f64e2ca3.png)

**Comment by patricksheedy** [comment]
This was due to invalid data in the QA database. A duplicate relation was included which caused the client to show up twice. I deleted the duplicate and it is now longer showing up in the site.

**Comment by hutch77** [comment]
The Commission the Broker is earning is still showing up in the tables in the summary lines, see screenshot:

![agent-report-errors2](https://user-images.githubusercontent.com/16338069/53925926-4706e280-4047-11e9-9655-6e5a4a447860.png)

That column has to be hidden because Agents shouldn't see what the broker is making and it also throws off the columns lining up since we removed it from the tables above the summary
