### ISSUE TITLE
Condo Commissions should be turned off

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#222]
On the broker's main page dashboard, hard-code the three entry fields to $0.00. We currently don't offer condo savings and not sure why this is pulling data - maybe old data it's pulling. The math should still work and take the Hotel Savings + $0 = just the Hotel Savings. That will still go in the two fields above it (Hotel/Condo Savings and Commissions Owed). 

![hard-code-0](https://user-images.githubusercontent.com/16338069/54951981-e4508a80-4f12-11e9-8f5e-9ff6f83d648e.png)

**Comment by patricksheedy** [comment]
Stored proc is returning condo information for some reason.

**Comment by hutch77** [comment]
Reopening this - The expectation was that zeroing out the Condo Commissions owed would change the math of the Total Commissions Owed section to be correct. It isn't:

![commissions-owed-error](https://user-images.githubusercontent.com/16338069/55432044-85fd5a80-5557-11e9-8c4f-6515f3a0dbac.png)

Commissions Owed _should_ be the sum of Hotel Commission Owed plus Condo Commission Owed.

**Comment by patricksheedy** [comment]
DashboardBroker stored proc updated to remove the condo amounts from the totals on both QA and prod. Code was changed to this:

	-- Issue 222: Removing condo commissions from total
	SET @MemberSavings = @HotelSavings -- + @CondoSavings;
	SET @CommissionsTotal = @HotelCommissionsTotal -- + @CondoCommissionsTotal;
	SET @CommissionsPaid = @HotelCommissionsPaid -- + @CondoCommissionsPaid;
	SET @CommissionsOwed = @HotelCommissionsOwed -- + @CondoCommissionsOwed;
