### ISSUE TITLE
Client Login: Campaigns not showing Campaigns

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#231]
At the bottom of the main Dashboard page for the Client (when a Client is logged in), it's showing a weird list of people instead of that Client's _Campaigns_.

**Comment by DennisRSI** [comment]
Done, you might want to open a new ticket to limit what the client can do when he clicks on campaigns.  Also I would like to test a client account with commissions owed so I can make sure it is working correctly.
