### ISSUE TITLE
Agent Main Dashboard: Third Row ("Brokers Overview") Isn't displaying Commissions Owed

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#232]
Two issues here in the **Agent Dashboard** - first of all, it should be "Agent Overview" instead of "Brokers Overview". Secondly, it isn't pulling in the Commission that the Agent is owed. Also, below that in Card Type Breakdown, it isn't showing any Commissions earned.

![Agent-Overview](https://user-images.githubusercontent.com/16338069/55810428-277f3180-5aad-11e9-88db-86fb63167796.png)

**Comment by DennisRSI** [comment]
Fixed
