### ISSUE TITLE
Agent Login: "Card Distribution by Client" table on Dashboard is empty

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#233]
The table at the bottom of the Agent's Dashboard (Card Distribution by Client) is not populating the Agent's Clients and Activation statuses.

![Card-Dist-by-Client](https://user-images.githubusercontent.com/16338069/55819010-88166a80-5abd-11e9-95ec-1add946a18cc.png)

**Comment by DennisRSI** [comment]
Made the update,  Also percentages were calculating incorrectly so I fixed that as well.
