### ISSUE TITLE
Investigate Cause: Commission Rate error message when adjusting Agent Commission

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#235]
Broker is trying to change an existing Agent's commission rate from 12% to 16%. He gets the error: The commission rate for this agent would be above the total commission you are getting for your company."

I'm not sure this error is valid, please investigate why this is happening. 

Broker is Ron White, Agent is Toney Vito Chimienti

**Comment by DennisRSI** [comment]
Fixed
