### ISSUE TITLE
Deactivation dialog text needs phone number

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#39]
The current text on the deactivation dialog says:

> Clients can be reactivated at any time by contact us at 888-888-8888 or emailing: brokersupport@travnow.com.

We need to update the text with the actual support phone number. Also verify that the email address is correct and working.

**Comment by hutch77** [comment]
Phone number: 770-854-1077. Working on the email for this

**Comment by hutch77** [comment]
The email brokersupport@travnow.com has been created as an alias and is being forwarded to both Jenny Powell and Robin Wolf.
