### ISSUE TITLE
Where to obtain the "Source" for reporting?

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#70]
There is a "Commission Report by Source" and "Production Report by Source". What is the "source"  for these reports? The mockup lists Alliance, RSI, Travel Source, Other.

**Comment by hutch77** [comment]
Dennis will provide

**Comment by patricksheedy** [comment]
"Alliance" is currently the only source. This will be hardcoded in the reports.
