### ISSUE TITLE
What user types should the Administrator Activation report allow in query?

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#76]
What user types should the Administrator be allowed to query? Looking at the mockups for the other reports:

Commission and Chargeback reports: Only allow querying by broker
Production report: Can query by Broker/client/agent

Should the Admin Activation query allow broker only? Or should it allow broker, client, and agents?

**Comment by hutch77** [comment]
Let's talk about this issue, I'm not sure I understand

**Comment by patricksheedy** [comment]
The Admin report allows querying by broker, client, agent. The activation report is completed so I'm closing this issue.
