### ISSUE TITLE
Client/Agent Activation Reports need to be created

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#80]
Need implementation (future milestone):
Client
Agent

Activation report implemented:
Admin
Broker

**Comment by patricksheedy** [comment]
Admin report blocked by #76

**Comment by hutch77** [comment]
Client and Agent should no longer be blocked since issue #75 is resolved.

**Comment by patricksheedy** [comment]
Activation Report: ReportActivations stored proc needs to be updated to support campaigns.

**Comment by patricksheedy** [comment]
Activation Report works for Agents.

Activation Report loads for Clients, but data is incorrect because ReportActivations proc does not separate data by campaigns (all campaigns show same number of activations).
