### ISSUE TITLE
Should Commission Report links be merged into one?

### ISSUE THREAD

**Issue by patricksheedy** [DennisRSI/AdminBrokerClientAgentPortal#87]
In the mockup the production reports were separate links depending on the "by" query. This was decided to change in the implementation to a single link.

Commission reports for Admin are separated in the mockup. Should these links also be merged?

**Comment by hutch77** [comment]
@patricksheedy  Yes, definitely - we should be consistent with the presentation unless there's something unique enough about the report to justify breaking it out in the nav.
